package com.github.meypod.al_azan.general_components

object Navigation {
    const val INTRO_1 = "intro1"
    const val INTRO_2 = "intro2"
    const val INTRO_3 = "intro3"
    const val INTRO_4 = "intro4"
    const val INTRO_5 = "intro5"
    const val INTRO_6 = "intro6"
    const val INTRO_7 = "intro7"
    const val INTRO_8 = "intro8"
    const val INTRO_9 = "intro9"
    const val INTRO_10 = "intro10"
    const val MAIN_SCREEN = "main_screen"
    const val ADJUSTMENTS = "adjustments"
    const val REMINDER = "reminder"
    const val QIBLA = "qibla"
    const val COUNTER = "counter"
    const val SETTINGS = "settings"
    const val ABOUT_US = "about_us"
    const val SOUND_SETTINGS = "sound_settings"
    const val CALCULATION_SETTINGS = "calculation_settings"
    const val LOCATION_SETTINGS = "location_settings"
    const val ADVANCED_CALCULATION_SETTINGS = "advanced_calculation_settings"
    const val INTERFACE_SETTINGS = "interface_settings"
    const val FIX_PROBLEMS_SETTINGS = "fix_problems_settings"
    const val WIDGET_SETTINGS = "widget_settings"
    const val BACKUP_SETTINGS = "backup_settings"
    const val MONTHLY_VIEW = "monthly_view"
    const val ADVANCED = "advanced"
    const val LOCATION_LIST = "location_list"
    const val MUAZZIN = "muazzin"
    const val NOTIFICATION_SOUND = "notification_sound"
    const val QIBLA_LOCATION = "qibla_location"
    const val QIBLA_COMPOSE = "qibla_compose"
    const val AZAN_ALARM = "azan_alarm"
}